In [4]:
import numpy as np
print(np.__version__)


1.21.5


In [29]:
a = np.random.default_rng(1)
a = a.random((5, 2, 3))
print(a)

[[[0.51182162 0.9504637  0.14415961]
  [0.94864945 0.31183145 0.42332645]]

 [[0.82770259 0.40919914 0.54959369]
  [0.02755911 0.75351311 0.53814331]]

 [[0.32973172 0.7884287  0.30319483]
  [0.45349789 0.1340417  0.40311299]]

 [[0.20345524 0.26231334 0.75036467]
  [0.28040876 0.48519097 0.9807372 ]]

 [[0.96165719 0.72478994 0.54122686]
  [0.2768912  0.16065201 0.96992541]]]


In [20]:
b=np.random.random((5,2,3))
print(b)

[[[0.92438514 0.69138486 0.14467876]
  [0.14457781 0.4781398  0.03147492]]

 [[0.19340094 0.81645695 0.23371294]
  [0.8853538  0.65344621 0.03920244]]

 [[0.33030084 0.13709947 0.54685176]
  [0.85237228 0.39825936 0.42845305]]

 [[0.424842   0.94666123 0.86994994]
  [0.04404233 0.65475864 0.1979312 ]]

 [[0.14695844 0.26401481 0.24483079]
  [0.61317582 0.04396823 0.25820461]]]


In [24]:
c=np.random.rand(5, 3, 3)
print(c)

[[[0.39390346 0.03802516 0.28175986]
  [0.57861618 0.64508595 0.64808796]
  [0.38317089 0.56633476 0.06841364]]

 [[0.30655247 0.3461457  0.9668053 ]
  [0.45269008 0.02107555 0.02952688]
  [0.73817148 0.21901727 0.32282449]]

 [[0.39229699 0.77139873 0.80364275]
  [0.00227336 0.34900008 0.94789958]
  [0.14218813 0.44218517 0.88688745]]

 [[0.80681906 0.44904396 0.79973618]
  [0.91103172 0.15873648 0.58670578]
  [0.36878458 0.14880941 0.58391964]]

 [[0.95562307 0.22512177 0.45524606]
  [0.77994824 0.81032041 0.28375806]
  [0.47755993 0.93865856 0.02820966]]]
