In [1]:
import numpy as np
print(np.__version__)


1.21.5


In [27]:
a = np.random.default_rng(1)
a = a.random((5, 2, 3))
print(a)

[[[0.51182162 0.9504637  0.14415961]
  [0.94864945 0.31183145 0.42332645]]

 [[0.82770259 0.40919914 0.54959369]
  [0.02755911 0.75351311 0.53814331]]

 [[0.32973172 0.7884287  0.30319483]
  [0.45349789 0.1340417  0.40311299]]

 [[0.20345524 0.26231334 0.75036467]
  [0.28040876 0.48519097 0.9807372 ]]

 [[0.96165719 0.72478994 0.54122686]
  [0.2768912  0.16065201 0.96992541]]]


In [20]:
a_alt1=np.random.random((5,2,3))
print(b)

[[[0.92438514 0.69138486 0.14467876]
  [0.14457781 0.4781398  0.03147492]]

 [[0.19340094 0.81645695 0.23371294]
  [0.8853538  0.65344621 0.03920244]]

 [[0.33030084 0.13709947 0.54685176]
  [0.85237228 0.39825936 0.42845305]]

 [[0.424842   0.94666123 0.86994994]
  [0.04404233 0.65475864 0.1979312 ]]

 [[0.14695844 0.26401481 0.24483079]
  [0.61317582 0.04396823 0.25820461]]]


In [10]:
a_alt2=np.random.rand(5, 2, 3)
print(c)

[[[0.96171628 0.62847127 0.69720958]
  [0.45382889 0.71645843 0.22041898]]

 [[0.57746505 0.30343186 0.57275549]
  [0.0500252  0.76920089 0.59092182]]

 [[0.2143467  0.14404171 0.95868709]
  [0.38093273 0.19920561 0.23085863]]

 [[0.94703123 0.8102385  0.32469632]
  [0.25555053 0.07297672 0.99997171]]

 [[0.40227644 0.83916486 0.92066155]
  [0.3334796  0.87687053 0.39768517]]]


In [28]:
b=np.full((5, 2, 3), 1, dtype=int)

In [23]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [ ]:
if a.any()==b.any():
    print("a and b are equal")
else:
    print('a and b are not equal')

In [29]:
x = np.concatenate((a, b), axis=0)
print(x)

[[[0.51182162 0.9504637  0.14415961]
  [0.94864945 0.31183145 0.42332645]]

 [[0.82770259 0.40919914 0.54959369]
  [0.02755911 0.75351311 0.53814331]]

 [[0.32973172 0.7884287  0.30319483]
  [0.45349789 0.1340417  0.40311299]]

 [[0.20345524 0.26231334 0.75036467]
  [0.28040876 0.48519097 0.9807372 ]]

 [[0.96165719 0.72478994 0.54122686]
  [0.2768912  0.16065201 0.96992541]]

 [[1.         1.         1.        ]
  [1.         1.         1.        ]]

 [[1.         1.         1.        ]
  [1.         1.         1.        ]]

 [[1.         1.         1.        ]
  [1.         1.         1.        ]]

 [[1.         1.         1.        ]
  [1.         1.         1.        ]]

 [[1.         1.         1.        ]
  [1.         1.         1.        ]]]
